### ISSUE TITLE
Formatting gets weird on iPhone

### ISSUE THREAD

**Issue by Maighdlyn** [LearnersGuild/curriculum#179]
# Bug Report

I found a problem on http://curriculum.learnersguild.org/phases/3/

The links to "view on github", "improve this page", etc are on top of "phase 3" when I'm looking at it on my iPhone SE. I took a screen shot but don't see anywhere to attach a photo in this bug report

**Comment by deadlyicon** [comment]
This is on my todo list. I'll hopefully get to it soon!

FYI you can drag and drop images into the GitHub Markdown editor.

**Comment by DianaVashti** [comment]
additional comments: On my iPhone 7 plus I am unable to open the navigation menu throughout the entire app.

**Comment by deadlyicon** [comment]
should be fixed now
