### ISSUE TITLE
Dead link for schedule in phase 1 curriculum

### ISSUE THREAD

**Issue by justinhaaheim** [LearnersGuild/curriculum#228]
The "schedule" link at the bottom of the [Phase 1 curriculum page](https://github.com/GuildCrafts/curriculum/tree/master/phases/1) gives a 404. What is this supposed to go to?

**Comment by deadlyicon** [comment]
it works from here https://curriculum.learnersguild.org/phases/1/ just not from GitHub. it links to an embeded google calendar

**Comment by deadlyicon** [comment]
we could add a `schedule.md` file here `https://github.com/LearnersGuild/curriculum/blob/master/phases/1/schedule` AKA `/phases/1/schedule/README.md` and have that just show a link to `https://curriculum.learnersguild.org/phases/1/schedule` for our github interface users.
