### ISSUE TITLE
Project team size (phase 3)

### ISSUE THREAD

**Issue by optomal7** [LearnersGuild/curriculum#230]
# Bug Report

Is it possible to see on the phase 3 page which projects are solo goals and which ones are not? It would be super helpful at times if there was a way to see at a glance.

**Comment by jrpool** [comment]
True, but on the other hand the Algorithm seems to be assigning team goals to solo Learners when they are the only Learners in their pool voting for them. (It did that this week to E.B. and me.) If solo vs. team has become a non-distinction, then there may be no need to show the classification.

**Comment by deadlyicon** [comment]
@prattsj @punitrathore is this an issue we can / should solve?

**Comment by prattsj** [comment]
Nope - the old project ssytem is being retired. Closing!

**Comment by prattsj** [comment]
Nope - the old project system is being retired. Can close!
