### ISSUE TITLE
Broken Goal URLs

### ISSUE THREAD

**Issue by prattsj** [LearnersGuild/curriculum#234]
In the API, a URL is provided in the response for https://curriculum.learnersguild.org/api/goals/418.json, but an attempt to request this results in an Internal Server Error.

![screen shot 2017-09-05 at 1 58 59 pm](https://user-images.githubusercontent.com/1890882/30075268-6b5bb368-9242-11e7-9b55-040c95e75ada.png)

![screen shot 2017-09-05 at 1 59 12 pm](https://user-images.githubusercontent.com/1890882/30075269-6cbea54e-9242-11e7-91a2-544dbd8662fd.png)

**Comment by deadlyicon** [comment]
fixed
