### ISSUE TITLE
Curriculum Page Refreshing Over and Over

### ISSUE THREAD

**Issue by allyface** [LearnersGuild/curriculum#242]
When I try to visit https://curriculum.learnersguild.org/modules/3-2-1-Contacts/contacts.js either directly or through the link in https://curriculum.learnersguild.org/modules/3-2-1-Contacts it takes me to an IDM login page (even though I'm already logged in) and it just keeps refreshing.

**Comment by deadlyicon** [comment]
I cannot recreate this. Can we sit down together and debug this?

**Comment by allyface** [comment]
It works for me now so I'll close this.
