### ISSUE TITLE
Write up a git workflow .md for people to follow when working on issues.

### ISSUE THREAD

**Issue by spencerdezartsmith** [LearnersGuild/curriculum#263]

**Comment by deadlyicon** [comment]
@spencerdezartsmith somehow there are 0 commits in this PR now. Can you please re-open this when its ready for review?

**Comment by deadlyicon** [comment]
@spencerdezartsmith where is the PR for this?

**Comment by spencerdezartsmith** [comment]
https://github.com/GuildCrafts/curriculum/pull/276/commits/5a7f1a00c705f8ae1fe0bf1506a4704c91cdcf10

**Comment by judytuna** [comment]
Can I close this?

**Comment by spencerdezartsmith** [comment]
Yep
