### ISSUE TITLE
Modules pages broken

### ISSUE THREAD

**Issue by prattsj** [LearnersGuild/curriculum#348]
https://curriculum.learnersguild.org/modules/Installfest

![screen shot 2017-09-28 at 11 58 18 am](https://user-images.githubusercontent.com/1890882/30977034-59efe02c-a444-11e7-8ae6-987523e4db24.png)

**Comment by prattsj** [comment]
Created a backup of the DB and ran a migration that appeared to not have been run. Seems to have resolved the issue. Would love some follow-up from @deadlyicon to confirm this was a suitable approach.

**Comment by deadlyicon** [comment]
thank you! totally my bad
