### ISSUE TITLE
tests ensuring learners can save their progress as they check off skills

### ISSUE THREAD

**Issue by judytuna** [LearnersGuild/curriculum#383]
The issue of checked skills not being saved was fixed in this PR: https://github.com/LearnersGuild/curriculum/pull/381

**Comment by jrpool** [comment]
I think that issue 376 already does this. I am currently working on that issue. In requires developing tests for /database/commands, which includes setSkillCheck, which is where the bug was.

**Comment by judytuna** [comment]
Thanks! https://github.com/LearnersGuild/curriculum/issues/376
