### ISSUE TITLE
Feature Request: Tracking phase progress tools

### ISSUE THREAD

**Issue by ontoneio** [LearnersGuild/curriculum#43]
-  breaking up the subtasks of the modules into time/completion contexts. I.e  To-Do, In-Progress, Finished. 
-  Set personal due dates on a project and per module basis
-  Gantt Chart based off project and module due dates set by user.
-  Module view shows at a glance: Module completion status, number of tasks left, personal due date.

**Comment by deadlyicon** [comment]
I added a progress bar to the skills pages :D

**Comment by ontoneio** [comment]
Very awesome! 
Forgive me. I meant to do some mock-ups and user stories. Just got caught up in all this learning. 
I will make more effort to get it done. I need to clarify on how to exactly go about doing a user story though.

**Comment by deadlyicon** [comment]
yeah learning is more important :)

**Comment by deadlyicon** [comment]
There is a bunch of stuff in the works around new ways to track progress. stay tuned!
