### ISSUE TITLE
Add more HTML and CSS skills to phase 1

### ISSUE THREAD

**Issue by deadlyicon** [LearnersGuild/curriculum#51]

**Comment by ontoneio** [comment]
Suggesting-
* [Creating Block Formatting Context](https://www.sitepoint.com/understanding-block-formatting-contexts-in-css/)
* [Implementing Media Queries](http://cssmediaqueries.com/)
* [Implementing Responsive Designs](https://developers.google.com/web/fundamentals/design-and-ui/responsive/)

**Comment by deadlyicon** [comment]
moved to private internal curriculum backlog
